package main

import (
	"fmt"
)

/*
การเกิด panic เป็นข้อผิดพลาดที่ไม่คาดคิดใน runtime ซึ่งทำให้โปรแกรมหยุดการทำงานโดยทันที ตัวอย่างที่พบบ่อย เช่น การหารด้วยศูนย์หรือการเข้าถึงดัชนีที่อยู่นอกขอบเขต เมื่อเกิด panic โปรแกรมจะหยุดทำงานและเรียกใช้ฟังก์ชันที่ถูก defer ไว้ จากนั้นควบคุมจะถูกส่งกลับไปยังผู้เรียก และกระบวนการนี้จะดำเนินต่อไปจนกระทั่งควบคุมไปถึง method แรกของ goroutine call stack สุดท้ายมันจะแสดง stack trace บนคอนโซล
*/

func main() {
	// แสดงข้อความเพื่อให้รู้ว่ากำลังหารด้วยศูนย์
	fmt.Println("Dividing by Zero")

	// กำหนดค่า a และ b
	a := 10
	b := 0

	// ทำการหารด้วยศูนย์ซึ่งจะเกิดข้อผิดพลาด panic
	c := a / b

	// โค้ดนี้จะไม่ทำงานเนื่องจากโปรแกรมจะหยุดที่ panic
	fmt.Println("Result:", c)
}

/*

 */
